### ISSUE TITLE
Use Maven plugin bnd-baseline-maven-plugin

### ISSUE THREAD

**Issue by gruberrolandvaltech** [orbinson/aem-groovy-console#28]
The versioning schema of Groovy console was always a big pain. It would be great if you can add semantic versioning.
This will enforce proper package and bundle versions based on the API changes. With this change it would also make sense to extract API classes to a separate bundle.

We use the same for AECU/AVS API bundles.

**Comment by bdhoine** [comment]
@gruberrolandvaltech very valid point, I also already discussed this with @royteeuwen that this would be a good improvement, we will add this in a next iteration ;)

**Comment by gruberrolandvaltech** [comment]
Semantic versioning would avoid having to specify the Groovy Console version in the import-package section. The versions would be automatically detected. And users of the API would clearly see if there are any breaking changes. ;-)

Not sure what the background of Sling is. Maybe they want to make sure that all bundles have the same version.
For AECU we have the check on the API bundle. But when a version change is required we also change the version of the whole project (to be consistent).

**Comment by bdhoine** [comment]
correct, problem with deploy to central in latest codebase due to javadoc error in api module, keeping this open until it's released on maven central also

**Comment by bdhoine** [comment]
@gruberrolandvaltech released 18.0.2 (and 18.0.3) but that version does not contain any changes.. 🙄
