### ISSUE TITLE
Minor UI issue: navigating through Services dropdown using ↑/↓ keys adds all the touched services to the console

### ISSUE THREAD

**Issue by senn** [orbinson/aem-groovy-console#43]
After searching for a Service using the Service/Adapter box at top right, you can navigate using ↑/↓ keys but when doing so all the services that you touch are added to the console.  Seems like that is not exactly what you want.

Ideally, one can navigate using the ↑/↓ keys and press \<enter\> to add a service to the console.

Tested with latest AEMaaCS SDK + groovyconsole 18.0.0

**Comment by bdhoine** [comment]
fixed in 19.0.4
