### ISSUE TITLE
Cloud pipeline package Overlap Issue

### ISSUE THREAD

**Issue by Narendiran100** [orbinson/aem-groovy-console#52]
Affected path /**apps/groovyconsole/clientlibs-aem** overlaps [aem-groovy-console-ui.apps:aem-groovy-console-ui.apps:19.0.4]

ui.apps have the filter as **/apps/groovyconsole** so it overlaps with the filter present in the **ui.apps.aem** module

**Comment by royteeuwen** [comment]
Solved in https://github.com/orbinson/aem-groovy-console/pull/61

**Comment by royteeuwen** [comment]
This has been solved in https://github.com/orbinson/aem-groovy-console/releases/tag/19.0.6

There is also a release https://github.com/orbinson/aem-groovy-console/releases/tag/19.0.7, which has an upgrade to the latest Groovy version (4.0.9 to 4.022) which includes support for JDK 21, 22 and 23
