### ISSUE TITLE
Link Groovy Console from the Tools Navigation

### ISSUE THREAD

**Issue by kwin** [orbinson/aem-groovy-console#56]
Currently there is no link to the groovy console. One needs to know/remember the URL. It should be linked from the Tools navigation (somewhere inside `/apps/cq/core/content/nav/tools`). Compare with https://github.com/Netcentric/accesscontroltool/blob/develop/accesscontroltool-apps-package/src/main/jcr_root/apps/cq/core/content/nav/tools/security/actool/.content.xml.

Probably it should be added to the section "General".

**Comment by royteeuwen** [comment]
This has been solved in https://github.com/orbinson/aem-groovy-console/releases/tag/19.0.6

There is also a release https://github.com/orbinson/aem-groovy-console/releases/tag/19.0.7, which has an upgrade to the latest Groovy version (4.0.9 to 4.022) which includes support for JDK 21, 22 and 23
