### ISSUE TITLE
Updating asm libraries

### ISSUE THREAD

**Issue by michalwedzik** [orbinson/aem-groovy-console#65]
Hi, I've tried running the Groovy console using Java 21 but ASM libraries don't support it. Could you update them to version 9.5 at least? 

`        <dependency>
            <groupId>org.ow2.asm</groupId>
            <artifactId>asm</artifactId>
            <version>9.4</version>
        </dependency>
        <dependency>
            <groupId>org.ow2.asm</groupId>
            <artifactId>asm-analysis</artifactId>
            <version>9.4</version>
        </dependency>
        <dependency>
            <groupId>org.ow2.asm</groupId>
            <artifactId>asm-commons</artifactId>
            <version>9.4</version>
        </dependency>
        <dependency>
            <groupId>org.ow2.asm</groupId>
            <artifactId>asm-util</artifactId>
            <version>9.4</version>
        </dependency>
        <dependency>
            <groupId>org.ow2.asm</groupId>
            <artifactId>asm-tree</artifactId>
            <version>9.4</version>
        </dependency>
`

Thanks!

**Comment by royteeuwen** [comment]
Of course! You will have to test it on an AEM that supports Java 21 though, I sadly enough don't have that (yet) ;)

**Comment by royteeuwen** [comment]
Fixed in https://github.com/orbinson/aem-groovy-console/releases/tag/19.0.8

**Comment by michalwedzik** [comment]
I've checked and it works. Thank you for the fast fix :)
