### ISSUE TITLE
Update to latest groovy version

### ISSUE THREAD

**Issue by royteeuwen** [orbinson/aem-groovy-console#7]
We are currently using Groovy 2.4.x, which is very old. It does not support any of the new features of Java 8+ (like streams / var / new switch statements / ...)

We should upgrade to Groovy 4.x, having the latest and the greatest

**Comment by royteeuwen** [comment]
@gruberrolandvaltech we are checking to upgrade to the latest Groovy version. We will make this release version 19.x because this is a mayor change. You are welcome to review as well, we hope that this will also be included in AECU

**Comment by gruberrolandvaltech** [comment]
I am in the process of moving to a different company. Please create a ticket on AECU's side once you release version 19. The new maintainer will pick it up then.

**Comment by royteeuwen** [comment]
Good luck on your new endeavours :)!

**Comment by royteeuwen** [comment]
Fixed with #38
